### ISSUE TITLE
Feature Request: VCS database.

### ISSUE THREAD

**Issue by itsDrac** [shubhexists/vault#11]
Hi,

I think we need to add a Version Control System Database for handling the things more efficiently.
this includes a check of restricting users to delete the current working branch.

for this database I would propose a `yml` file
something like `config.yml` in `.vault/` folder.

Let me know your thoughts on this.

**Comment by shubhexists** [comment]
Hi, currently there is a file called `CurrentDir` in the `.vault` directory that keeps a track of the current branch.
![Screenshot from 2023-11-30 02-38-26](https://github.com/shubhexists/vault/assets/110319892/dfba8f45-8c98-4a5f-9813-40907d8bf418)

In the above image, initially the current working directory is `main2` so `cat CurrentDir` was returning `main2`  
  which after the switch command becomes `main` so `cat CurrentDir` now returns `main`.
I used a file with no extension because there was only 1 thing to store..

However, 1 reason I thing we might shift to `.yml` is that, we might meed to store multiple things later (for example say commit history or maybe we can store the path of the vault so that we do not need to call  `std::env::current_dir()` multiple times ..). 
It would be easier to store multiple things in `.yml`

**Comment by shubhexists** [comment]
In my opinion we can shift to a `.yml` file storing 2 things currently..
the directory of the vault... and the current active branch

**Comment by itsDrac** [comment]
we can have commit message as well in the `config.yml` file.

here is the tree structure that i am thinking
```
.vault/
  | main_branch/
    | config.yml
  | init.yml
```

in `init.yml` we can store global data. like current working branch
and in `config.yml` we could store branch specific data like commit message.

**Comment by shubhexists** [comment]
Hmm this seems correct in the long term when we actually start tracking changes too... We would require history of commits per branch...
Would you like to work on it?

**Comment by shubhexists** [comment]
Closing this too as #12 is closed
